services:
  web:
    build:
      context: app
      target: development
    ports:
      - "8083:3000"
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL:-http://host.docker.internal:8000/api}
      VITE_APP_TITLE: ${VITE_APP_TITLE:-Blog Admin}
    volumes:
      - ./app:/project
      - /project/node_modules
