services:
  web:
    build:
      context: app
      target: development
    ports:
      - "8083:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL:-http://host.docker.internal:3925/api}
    volumes:
      - ./app:/project
      - /project/node_modules
